// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type File struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Size        int         `json:"size"`
	ContentType string      `json:"contentType"`
	CreatedAt   string      `json:"createdAt"`
	FileData    *string     `json:"fileData,omitempty"`
	Metadata    []*Metadata `json:"metadata,omitempty"`
}

type FileInput struct {
	Name        string           `json:"name"`
	Size        int              `json:"size"`
	ContentType string           `json:"contentType"`
	FileData    string           `json:"fileData"`
	Metadata    []*MetadataInput `json:"metadata,omitempty"`
}

type Metadata struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type MetadataInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Mutation struct {
}

type Node struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	ParentID  *string `json:"parentId,omitempty"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
	Children  []*Node `json:"children,omitempty"`
	Parent    *Node   `json:"parent,omitempty"`
}

type NodeInput struct {
	Name     string  `json:"name"`
	ParentID *string `json:"parentId,omitempty"`
}

type NodeUpdateInput struct {
	Name     *string `json:"name,omitempty"`
	ParentID *string `json:"parentId,omitempty"`
}

type Query struct {
}

type Todo struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	Done   bool   `json:"done"`
	User   *User  `json:"user"`
	userID string `json:"-"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
